# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='raft.proto',
    package='rafts',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\nraft.proto\x12\x05rafts\"$\n\x04Ping\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\x0e\n\x06peerId\x18\x02 \x01(\t\"\x15\n\x04Pong\x12\r\n\x05state\x18\x01 \x01(\x08\"W\n\x07ReqVote\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\")\n\x04Vote\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"D\n\x07\x45ntries\x12\x0b\n\x03opt\x18\x01 \x01(\t\x12\x0b\n\x03obj\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\x94\x01\n\x10ReqAppendEntries\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.rafts.Entries\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"1\n\x10ResAppendEntries\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xa4\x01\n\tServeRaft\x12-\n\x0crequest_vote\x12\x0e.rafts.ReqVote\x1a\x0b.rafts.Vote\"\x00\x12\x44\n\x0e\x61ppend_entries\x12\x17.rafts.ReqAppendEntries\x1a\x17.rafts.ResAppendEntries\"\x00\x12\"\n\x04ping\x12\x0b.rafts.Ping\x1a\x0b.rafts.Pong\"\x00\x62\x06proto3')
)

_PING = _descriptor.Descriptor(
    name='Ping',
    full_name='rafts.Ping',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='addr', full_name='rafts.Ping.addr', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='peerId', full_name='rafts.Ping.peerId', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=21,
    serialized_end=57,
)

_PONG = _descriptor.Descriptor(
    name='Pong',
    full_name='rafts.Pong',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='state', full_name='rafts.Pong.state', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=59,
    serialized_end=80,
)

_REQVOTE = _descriptor.Descriptor(
    name='ReqVote',
    full_name='rafts.ReqVote',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='term', full_name='rafts.ReqVote.term', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='candidateId', full_name='rafts.ReqVote.candidateId', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lastLogIndex', full_name='rafts.ReqVote.lastLogIndex', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lastLogTerm', full_name='rafts.ReqVote.lastLogTerm', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=82,
    serialized_end=169,
)

_VOTE = _descriptor.Descriptor(
    name='Vote',
    full_name='rafts.Vote',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='term', full_name='rafts.Vote.term', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='voteGranted', full_name='rafts.Vote.voteGranted', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=171,
    serialized_end=212,
)

_ENTRIES = _descriptor.Descriptor(
    name='Entries',
    full_name='rafts.Entries',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='opt', full_name='rafts.Entries.opt', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='obj', full_name='rafts.Entries.obj', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='args', full_name='rafts.Entries.args', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='rafts.Entries.timestamp', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=214,
    serialized_end=282,
)

_REQAPPENDENTRIES = _descriptor.Descriptor(
    name='ReqAppendEntries',
    full_name='rafts.ReqAppendEntries',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='term', full_name='rafts.ReqAppendEntries.term', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='leaderId', full_name='rafts.ReqAppendEntries.leaderId', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='prevLogIndex', full_name='rafts.ReqAppendEntries.prevLogIndex', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='prevLogTerm', full_name='rafts.ReqAppendEntries.prevLogTerm', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='entries', full_name='rafts.ReqAppendEntries.entries', index=4,
            number=5, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='leaderCommit', full_name='rafts.ReqAppendEntries.leaderCommit', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=285,
    serialized_end=433,
)

_RESAPPENDENTRIES = _descriptor.Descriptor(
    name='ResAppendEntries',
    full_name='rafts.ResAppendEntries',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='term', full_name='rafts.ResAppendEntries.term', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='success', full_name='rafts.ResAppendEntries.success', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=435,
    serialized_end=484,
)

_REQAPPENDENTRIES.fields_by_name['entries'].message_type = _ENTRIES
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['ReqVote'] = _REQVOTE
DESCRIPTOR.message_types_by_name['Vote'] = _VOTE
DESCRIPTOR.message_types_by_name['Entries'] = _ENTRIES
DESCRIPTOR.message_types_by_name['ReqAppendEntries'] = _REQAPPENDENTRIES
DESCRIPTOR.message_types_by_name['ResAppendEntries'] = _RESAPPENDENTRIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
    DESCRIPTOR=_PING,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.Ping)
))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
    DESCRIPTOR=_PONG,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.Pong)
))
_sym_db.RegisterMessage(Pong)

ReqVote = _reflection.GeneratedProtocolMessageType('ReqVote', (_message.Message,), dict(
    DESCRIPTOR=_REQVOTE,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.ReqVote)
))
_sym_db.RegisterMessage(ReqVote)

Vote = _reflection.GeneratedProtocolMessageType('Vote', (_message.Message,), dict(
    DESCRIPTOR=_VOTE,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.Vote)
))
_sym_db.RegisterMessage(Vote)

Entries = _reflection.GeneratedProtocolMessageType('Entries', (_message.Message,), dict(
    DESCRIPTOR=_ENTRIES,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.Entries)
))
_sym_db.RegisterMessage(Entries)

ReqAppendEntries = _reflection.GeneratedProtocolMessageType('ReqAppendEntries', (_message.Message,), dict(
    DESCRIPTOR=_REQAPPENDENTRIES,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.ReqAppendEntries)
))
_sym_db.RegisterMessage(ReqAppendEntries)

ResAppendEntries = _reflection.GeneratedProtocolMessageType('ResAppendEntries', (_message.Message,), dict(
    DESCRIPTOR=_RESAPPENDENTRIES,
    __module__='raft_pb2'
    # @@protoc_insertion_point(class_scope:rafts.ResAppendEntries)
))
_sym_db.RegisterMessage(ResAppendEntries)

_SERVERAFT = _descriptor.ServiceDescriptor(
    name='ServeRaft',
    full_name='rafts.ServeRaft',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=487,
    serialized_end=651,
    methods=[
        _descriptor.MethodDescriptor(
            name='request_vote',
            full_name='rafts.ServeRaft.request_vote',
            index=0,
            containing_service=None,
            input_type=_REQVOTE,
            output_type=_VOTE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='append_entries',
            full_name='rafts.ServeRaft.append_entries',
            index=1,
            containing_service=None,
            input_type=_REQAPPENDENTRIES,
            output_type=_RESAPPENDENTRIES,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='ping',
            full_name='rafts.ServeRaft.ping',
            index=2,
            containing_service=None,
            input_type=_PING,
            output_type=_PONG,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SERVERAFT)

DESCRIPTOR.services_by_name['ServeRaft'] = _SERVERAFT

# @@protoc_insertion_point(module_scope)
