# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import raft.protobuf.raft_pb2 as raft__pb2


class ServeRaftStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.request_vote = channel.unary_unary(
            '/rafts.ServeRaft/request_vote',
            request_serializer=raft__pb2.ReqVote.SerializeToString,
            response_deserializer=raft__pb2.Vote.FromString,
        )
        self.append_entries = channel.unary_unary(
            '/rafts.ServeRaft/append_entries',
            request_serializer=raft__pb2.ReqAppendEntries.SerializeToString,
            response_deserializer=raft__pb2.ResAppendEntries.FromString,
        )
        self.ping = channel.unary_unary(
            '/rafts.ServeRaft/ping',
            request_serializer=raft__pb2.Ping.SerializeToString,
            response_deserializer=raft__pb2.Pong.FromString,
        )


class ServeRaftServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def request_vote(self, request, context):
        """请求follower为自己投票
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def append_entries(self, request, context):
        """同步日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServeRaftServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'request_vote': grpc.unary_unary_rpc_method_handler(
            servicer.request_vote,
            request_deserializer=raft__pb2.ReqVote.FromString,
            response_serializer=raft__pb2.Vote.SerializeToString,
        ),
        'append_entries': grpc.unary_unary_rpc_method_handler(
            servicer.append_entries,
            request_deserializer=raft__pb2.ReqAppendEntries.FromString,
            response_serializer=raft__pb2.ResAppendEntries.SerializeToString,
        ),
        'ping': grpc.unary_unary_rpc_method_handler(
            servicer.ping,
            request_deserializer=raft__pb2.Ping.FromString,
            response_serializer=raft__pb2.Pong.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'rafts.ServeRaft', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
